backend:
  name: github
  repo: yasisoft/my-hugo-site
  branch: main
  site_domain: yasisoft.github.io
  auth_endpoint: https://auth.decapcms.org
  base_url: https://yasisoft.github.io/my-hugo-site
  client_id: Ov23lims3dRZp9vJ8Z7U

media_folder: "static/uploads"
public_folder: "/my-hugo-site/uploads"

collections:
  - name: "author1"
    label: "Author 11 Posts"
    folder: "content/author1"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "author2"
    label: "Author 2 Posts"
    folder: "content/author2"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
